import { readdirSync, readFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const publicCopyDirectories = ["src/landing", "src/routes"];
const publicCopyFiles = ["src/lib/site.ts", "convex/enquiries.ts"];
const textExtensions = new Set([".css", ".js", ".jsx", ".ts", ".tsx"]);
const longDashPattern = /[\u2013\u2014]/g;

function collectSourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);

    if (entry.isDirectory()) {
      return collectSourceFiles(path);
    }

    return textExtensions.has(extname(entry.name)) ? [path] : [];
  });
}

const matches: string[] = [];

for (const file of [...publicCopyDirectories.flatMap(collectSourceFiles), ...publicCopyFiles]) {
  const contents = readFileSync(file, "utf8");

  if (contents.includes("// AUTO-GENERATED by @lovable.dev/mcp-js")) {
    continue;
  }

  contents.split(/\r?\n/).forEach((line, lineIndex) => {
    for (const match of line.matchAll(longDashPattern)) {
      matches.push(
        `${relative(process.cwd(), file)}:${lineIndex + 1}:${(match.index ?? 0) + 1} contains ${JSON.stringify(match[0])}`,
      );
    }
  });
}

if (matches.length > 0) {
  console.error("Public copy contains an em dash or en dash:");
  console.error(matches.join("\n"));
  process.exit(1);
}

console.log("Public-copy check passed: no em dashes or en dashes found.");
