/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ConsultationsIdRouteImport } from './routes/consultations.$id'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as FamilyHelpRouteImport } from './routes/family.help'
import { Route as ConsultationsIdIndexRouteImport } from './routes/consultations.$id.index'
import { Route as ConsultationsIdDraftRouteImport } from './routes/consultations.$id.draft'
import { Route as ConsultationsIdNeedsRouteImport } from './routes/consultations.$id.needs'
import { Route as ConsultationsIdSubmitRouteImport } from './routes/consultations.$id.submit'
import { Route as FamilyCasesIdRouteImport } from './routes/family.cases.$id'
import { Route as FamilyCasesIdIndexRouteImport } from './routes/family.cases.$id.index'
import { Route as FamilyCasesIdAssistantRouteImport } from './routes/family.cases.$id.assistant'
import { Route as FamilyCasesIdConfirmationRouteImport } from './routes/family.cases.$id.confirmation'
import { Route as FamilyCasesIdDocumentsRouteImport } from './routes/family.cases.$id.documents'
import { Route as FamilyCasesIdIssuesRouteImport } from './routes/family.cases.$id.issues'
import { Route as FamilyCasesIdPlanRouteImport } from './routes/family.cases.$id.plan'
import { Route as FamilyCasesIdResponseRouteImport } from './routes/family.cases.$id.response'
import { Route as FamilyCasesIdSupportRouteImport } from './routes/family.cases.$id.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsIdRoute = ConsultationsIdRouteImport.update({
  id: '/consultations/$id',
  path: '/consultations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyHelpRoute = FamilyHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => FamilyRoute,
} as any)
const ConsultationsIdIndexRoute = ConsultationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdDraftRoute = ConsultationsIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdNeedsRoute = ConsultationsIdNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdSubmitRoute = ConsultationsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const FamilyCasesIdRoute = FamilyCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyCasesIdIndexRoute = FamilyCasesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdAssistantRoute = FamilyCasesIdAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdConfirmationRoute =
  FamilyCasesIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => FamilyCasesIdRoute,
  } as any)
const FamilyCasesIdDocumentsRoute = FamilyCasesIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdIssuesRoute = FamilyCasesIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdPlanRoute = FamilyCasesIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdResponseRoute = FamilyCasesIdResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdSupportRoute = FamilyCasesIdSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/family': typeof FamilyRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/consultations/$id': typeof ConsultationsIdRouteWithChildren
  '/family/help': typeof FamilyHelpRoute
  '/family/': typeof FamilyIndexRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/family/cases/$id': typeof FamilyCasesIdRouteWithChildren
  '/consultations/$id/': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id/': typeof FamilyCasesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/family/help': typeof FamilyHelpRoute
  '/family': typeof FamilyIndexRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/consultations/$id': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id': typeof FamilyCasesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/family': typeof FamilyRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/consultations/$id': typeof ConsultationsIdRouteWithChildren
  '/family/help': typeof FamilyHelpRoute
  '/family/': typeof FamilyIndexRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/family/cases/$id': typeof FamilyCasesIdRouteWithChildren
  '/consultations/$id/': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id/': typeof FamilyCasesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/family'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/consultations/$id'
    | '/family/help'
    | '/family/'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/family/cases/$id'
    | '/consultations/$id/'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/family/help'
    | '/family'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/consultations/$id'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/family'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/consultations/$id'
    | '/family/help'
    | '/family/'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/family/cases/$id'
    | '/consultations/$id/'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  ConsultationsIdRoute: typeof ConsultationsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations/$id': {
      id: '/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof ConsultationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/help': {
      id: '/family/help'
      path: '/help'
      fullPath: '/family/help'
      preLoaderRoute: typeof FamilyHelpRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/consultations/$id/': {
      id: '/consultations/$id/'
      path: '/'
      fullPath: '/consultations/$id/'
      preLoaderRoute: typeof ConsultationsIdIndexRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/draft': {
      id: '/consultations/$id/draft'
      path: '/draft'
      fullPath: '/consultations/$id/draft'
      preLoaderRoute: typeof ConsultationsIdDraftRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/needs': {
      id: '/consultations/$id/needs'
      path: '/needs'
      fullPath: '/consultations/$id/needs'
      preLoaderRoute: typeof ConsultationsIdNeedsRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/submit': {
      id: '/consultations/$id/submit'
      path: '/submit'
      fullPath: '/consultations/$id/submit'
      preLoaderRoute: typeof ConsultationsIdSubmitRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/family/cases/$id': {
      id: '/family/cases/$id'
      path: '/cases/$id'
      fullPath: '/family/cases/$id'
      preLoaderRoute: typeof FamilyCasesIdRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/cases/$id/': {
      id: '/family/cases/$id/'
      path: '/'
      fullPath: '/family/cases/$id/'
      preLoaderRoute: typeof FamilyCasesIdIndexRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/assistant': {
      id: '/family/cases/$id/assistant'
      path: '/assistant'
      fullPath: '/family/cases/$id/assistant'
      preLoaderRoute: typeof FamilyCasesIdAssistantRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/confirmation': {
      id: '/family/cases/$id/confirmation'
      path: '/confirmation'
      fullPath: '/family/cases/$id/confirmation'
      preLoaderRoute: typeof FamilyCasesIdConfirmationRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/documents': {
      id: '/family/cases/$id/documents'
      path: '/documents'
      fullPath: '/family/cases/$id/documents'
      preLoaderRoute: typeof FamilyCasesIdDocumentsRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/issues': {
      id: '/family/cases/$id/issues'
      path: '/issues'
      fullPath: '/family/cases/$id/issues'
      preLoaderRoute: typeof FamilyCasesIdIssuesRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/plan': {
      id: '/family/cases/$id/plan'
      path: '/plan'
      fullPath: '/family/cases/$id/plan'
      preLoaderRoute: typeof FamilyCasesIdPlanRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/response': {
      id: '/family/cases/$id/response'
      path: '/response'
      fullPath: '/family/cases/$id/response'
      preLoaderRoute: typeof FamilyCasesIdResponseRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/support': {
      id: '/family/cases/$id/support'
      path: '/support'
      fullPath: '/family/cases/$id/support'
      preLoaderRoute: typeof FamilyCasesIdSupportRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
  }
}

interface FamilyCasesIdRouteChildren {
  FamilyCasesIdAssistantRoute: typeof FamilyCasesIdAssistantRoute
  FamilyCasesIdConfirmationRoute: typeof FamilyCasesIdConfirmationRoute
  FamilyCasesIdDocumentsRoute: typeof FamilyCasesIdDocumentsRoute
  FamilyCasesIdIssuesRoute: typeof FamilyCasesIdIssuesRoute
  FamilyCasesIdPlanRoute: typeof FamilyCasesIdPlanRoute
  FamilyCasesIdResponseRoute: typeof FamilyCasesIdResponseRoute
  FamilyCasesIdSupportRoute: typeof FamilyCasesIdSupportRoute
  FamilyCasesIdIndexRoute: typeof FamilyCasesIdIndexRoute
}

const FamilyCasesIdRouteChildren: FamilyCasesIdRouteChildren = {
  FamilyCasesIdAssistantRoute: FamilyCasesIdAssistantRoute,
  FamilyCasesIdConfirmationRoute: FamilyCasesIdConfirmationRoute,
  FamilyCasesIdDocumentsRoute: FamilyCasesIdDocumentsRoute,
  FamilyCasesIdIssuesRoute: FamilyCasesIdIssuesRoute,
  FamilyCasesIdPlanRoute: FamilyCasesIdPlanRoute,
  FamilyCasesIdResponseRoute: FamilyCasesIdResponseRoute,
  FamilyCasesIdSupportRoute: FamilyCasesIdSupportRoute,
  FamilyCasesIdIndexRoute: FamilyCasesIdIndexRoute,
}

const FamilyCasesIdRouteWithChildren = FamilyCasesIdRoute._addFileChildren(
  FamilyCasesIdRouteChildren,
)

interface FamilyRouteChildren {
  FamilyHelpRoute: typeof FamilyHelpRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  FamilyCasesIdRoute: typeof FamilyCasesIdRouteWithChildren
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyHelpRoute: FamilyHelpRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  FamilyCasesIdRoute: FamilyCasesIdRouteWithChildren,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface ConsultationsIdRouteChildren {
  ConsultationsIdDraftRoute: typeof ConsultationsIdDraftRoute
  ConsultationsIdNeedsRoute: typeof ConsultationsIdNeedsRoute
  ConsultationsIdSubmitRoute: typeof ConsultationsIdSubmitRoute
  ConsultationsIdIndexRoute: typeof ConsultationsIdIndexRoute
}

const ConsultationsIdRouteChildren: ConsultationsIdRouteChildren = {
  ConsultationsIdDraftRoute: ConsultationsIdDraftRoute,
  ConsultationsIdNeedsRoute: ConsultationsIdNeedsRoute,
  ConsultationsIdSubmitRoute: ConsultationsIdSubmitRoute,
  ConsultationsIdIndexRoute: ConsultationsIdIndexRoute,
}

const ConsultationsIdRouteWithChildren = ConsultationsIdRoute._addFileChildren(
  ConsultationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FamilyRoute: FamilyRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  ConsultationsIdRoute: ConsultationsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
