/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ConsultationsIdRouteImport } from './routes/consultations.$id'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as FamilyHelpRouteImport } from './routes/family.help'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ConsultationsIdIndexRouteImport } from './routes/consultations.$id.index'
import { Route as ConsultationsIdDraftRouteImport } from './routes/consultations.$id.draft'
import { Route as ConsultationsIdNeedsRouteImport } from './routes/consultations.$id.needs'
import { Route as ConsultationsIdSubmitRouteImport } from './routes/consultations.$id.submit'
import { Route as FamilyCasesIdRouteImport } from './routes/family.cases.$id'
import { Route as FamilyCasesIdIndexRouteImport } from './routes/family.cases.$id.index'
import { Route as FamilyCasesIdAssistantRouteImport } from './routes/family.cases.$id.assistant'
import { Route as FamilyCasesIdConfirmationRouteImport } from './routes/family.cases.$id.confirmation'
import { Route as FamilyCasesIdDocumentsRouteImport } from './routes/family.cases.$id.documents'
import { Route as FamilyCasesIdIssuesRouteImport } from './routes/family.cases.$id.issues'
import { Route as FamilyCasesIdPlanRouteImport } from './routes/family.cases.$id.plan'
import { Route as FamilyCasesIdResponseRouteImport } from './routes/family.cases.$id.response'
import { Route as FamilyCasesIdSupportRouteImport } from './routes/family.cases.$id.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ConsultationsIdRoute = ConsultationsIdRouteImport.update({
  id: '/consultations/$id',
  path: '/consultations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyHelpRoute = FamilyHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => FamilyRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultationsIdIndexRoute = ConsultationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdDraftRoute = ConsultationsIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdNeedsRoute = ConsultationsIdNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const ConsultationsIdSubmitRoute = ConsultationsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ConsultationsIdRoute,
} as any)
const FamilyCasesIdRoute = FamilyCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyCasesIdIndexRoute = FamilyCasesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdAssistantRoute = FamilyCasesIdAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdConfirmationRoute =
  FamilyCasesIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => FamilyCasesIdRoute,
  } as any)
const FamilyCasesIdDocumentsRoute = FamilyCasesIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdIssuesRoute = FamilyCasesIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdPlanRoute = FamilyCasesIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdResponseRoute = FamilyCasesIdResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)
const FamilyCasesIdSupportRoute = FamilyCasesIdSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => FamilyCasesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRouteWithChildren
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/consultations/$id': typeof ConsultationsIdRouteWithChildren
  '/family/help': typeof FamilyHelpRoute
  '/blog/': typeof BlogIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/family/cases/$id': typeof FamilyCasesIdRouteWithChildren
  '/consultations/$id/': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id/': typeof FamilyCasesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/family/help': typeof FamilyHelpRoute
  '/blog': typeof BlogIndexRoute
  '/family': typeof FamilyIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/consultations/$id': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id': typeof FamilyCasesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRouteWithChildren
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/consultations/$id': typeof ConsultationsIdRouteWithChildren
  '/family/help': typeof FamilyHelpRoute
  '/blog/': typeof BlogIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/consultations/$id/draft': typeof ConsultationsIdDraftRoute
  '/consultations/$id/needs': typeof ConsultationsIdNeedsRoute
  '/consultations/$id/submit': typeof ConsultationsIdSubmitRoute
  '/family/cases/$id': typeof FamilyCasesIdRouteWithChildren
  '/consultations/$id/': typeof ConsultationsIdIndexRoute
  '/family/cases/$id/assistant': typeof FamilyCasesIdAssistantRoute
  '/family/cases/$id/confirmation': typeof FamilyCasesIdConfirmationRoute
  '/family/cases/$id/documents': typeof FamilyCasesIdDocumentsRoute
  '/family/cases/$id/issues': typeof FamilyCasesIdIssuesRoute
  '/family/cases/$id/plan': typeof FamilyCasesIdPlanRoute
  '/family/cases/$id/response': typeof FamilyCasesIdResponseRoute
  '/family/cases/$id/support': typeof FamilyCasesIdSupportRoute
  '/family/cases/$id/': typeof FamilyCasesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/calendar'
    | '/changelog'
    | '/contact'
    | '/family'
    | '/help'
    | '/integrations'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/workshops'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/consultations/$id'
    | '/family/help'
    | '/blog/'
    | '/family/'
    | '/.mcp/invoke-tool/$tool'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/family/cases/$id'
    | '/consultations/$id/'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/changelog'
    | '/contact'
    | '/help'
    | '/integrations'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/workshops'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/family/help'
    | '/blog'
    | '/family'
    | '/.mcp/invoke-tool/$tool'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/consultations/$id'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/calendar'
    | '/changelog'
    | '/contact'
    | '/family'
    | '/help'
    | '/integrations'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/workshops'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/consultations/$id'
    | '/family/help'
    | '/blog/'
    | '/family/'
    | '/.mcp/invoke-tool/$tool'
    | '/consultations/$id/draft'
    | '/consultations/$id/needs'
    | '/consultations/$id/submit'
    | '/family/cases/$id'
    | '/consultations/$id/'
    | '/family/cases/$id/assistant'
    | '/family/cases/$id/confirmation'
    | '/family/cases/$id/documents'
    | '/family/cases/$id/issues'
    | '/family/cases/$id/plan'
    | '/family/cases/$id/response'
    | '/family/cases/$id/support'
    | '/family/cases/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  HelpRoute: typeof HelpRoute
  IntegrationsRoute: typeof IntegrationsRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  WorkshopsRoute: typeof WorkshopsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ConsultationsIdRoute: typeof ConsultationsIdRouteWithChildren
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/consultations/$id': {
      id: '/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof ConsultationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/help': {
      id: '/family/help'
      path: '/help'
      fullPath: '/family/help'
      preLoaderRoute: typeof FamilyHelpRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations/$id/': {
      id: '/consultations/$id/'
      path: '/'
      fullPath: '/consultations/$id/'
      preLoaderRoute: typeof ConsultationsIdIndexRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/draft': {
      id: '/consultations/$id/draft'
      path: '/draft'
      fullPath: '/consultations/$id/draft'
      preLoaderRoute: typeof ConsultationsIdDraftRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/needs': {
      id: '/consultations/$id/needs'
      path: '/needs'
      fullPath: '/consultations/$id/needs'
      preLoaderRoute: typeof ConsultationsIdNeedsRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/consultations/$id/submit': {
      id: '/consultations/$id/submit'
      path: '/submit'
      fullPath: '/consultations/$id/submit'
      preLoaderRoute: typeof ConsultationsIdSubmitRouteImport
      parentRoute: typeof ConsultationsIdRoute
    }
    '/family/cases/$id': {
      id: '/family/cases/$id'
      path: '/cases/$id'
      fullPath: '/family/cases/$id'
      preLoaderRoute: typeof FamilyCasesIdRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/cases/$id/': {
      id: '/family/cases/$id/'
      path: '/'
      fullPath: '/family/cases/$id/'
      preLoaderRoute: typeof FamilyCasesIdIndexRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/assistant': {
      id: '/family/cases/$id/assistant'
      path: '/assistant'
      fullPath: '/family/cases/$id/assistant'
      preLoaderRoute: typeof FamilyCasesIdAssistantRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/confirmation': {
      id: '/family/cases/$id/confirmation'
      path: '/confirmation'
      fullPath: '/family/cases/$id/confirmation'
      preLoaderRoute: typeof FamilyCasesIdConfirmationRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/documents': {
      id: '/family/cases/$id/documents'
      path: '/documents'
      fullPath: '/family/cases/$id/documents'
      preLoaderRoute: typeof FamilyCasesIdDocumentsRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/issues': {
      id: '/family/cases/$id/issues'
      path: '/issues'
      fullPath: '/family/cases/$id/issues'
      preLoaderRoute: typeof FamilyCasesIdIssuesRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/plan': {
      id: '/family/cases/$id/plan'
      path: '/plan'
      fullPath: '/family/cases/$id/plan'
      preLoaderRoute: typeof FamilyCasesIdPlanRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/response': {
      id: '/family/cases/$id/response'
      path: '/response'
      fullPath: '/family/cases/$id/response'
      preLoaderRoute: typeof FamilyCasesIdResponseRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
    '/family/cases/$id/support': {
      id: '/family/cases/$id/support'
      path: '/support'
      fullPath: '/family/cases/$id/support'
      preLoaderRoute: typeof FamilyCasesIdSupportRouteImport
      parentRoute: typeof FamilyCasesIdRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface FamilyCasesIdRouteChildren {
  FamilyCasesIdAssistantRoute: typeof FamilyCasesIdAssistantRoute
  FamilyCasesIdConfirmationRoute: typeof FamilyCasesIdConfirmationRoute
  FamilyCasesIdDocumentsRoute: typeof FamilyCasesIdDocumentsRoute
  FamilyCasesIdIssuesRoute: typeof FamilyCasesIdIssuesRoute
  FamilyCasesIdPlanRoute: typeof FamilyCasesIdPlanRoute
  FamilyCasesIdResponseRoute: typeof FamilyCasesIdResponseRoute
  FamilyCasesIdSupportRoute: typeof FamilyCasesIdSupportRoute
  FamilyCasesIdIndexRoute: typeof FamilyCasesIdIndexRoute
}

const FamilyCasesIdRouteChildren: FamilyCasesIdRouteChildren = {
  FamilyCasesIdAssistantRoute: FamilyCasesIdAssistantRoute,
  FamilyCasesIdConfirmationRoute: FamilyCasesIdConfirmationRoute,
  FamilyCasesIdDocumentsRoute: FamilyCasesIdDocumentsRoute,
  FamilyCasesIdIssuesRoute: FamilyCasesIdIssuesRoute,
  FamilyCasesIdPlanRoute: FamilyCasesIdPlanRoute,
  FamilyCasesIdResponseRoute: FamilyCasesIdResponseRoute,
  FamilyCasesIdSupportRoute: FamilyCasesIdSupportRoute,
  FamilyCasesIdIndexRoute: FamilyCasesIdIndexRoute,
}

const FamilyCasesIdRouteWithChildren = FamilyCasesIdRoute._addFileChildren(
  FamilyCasesIdRouteChildren,
)

interface FamilyRouteChildren {
  FamilyHelpRoute: typeof FamilyHelpRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  FamilyCasesIdRoute: typeof FamilyCasesIdRouteWithChildren
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyHelpRoute: FamilyHelpRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  FamilyCasesIdRoute: FamilyCasesIdRouteWithChildren,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface ConsultationsIdRouteChildren {
  ConsultationsIdDraftRoute: typeof ConsultationsIdDraftRoute
  ConsultationsIdNeedsRoute: typeof ConsultationsIdNeedsRoute
  ConsultationsIdSubmitRoute: typeof ConsultationsIdSubmitRoute
  ConsultationsIdIndexRoute: typeof ConsultationsIdIndexRoute
}

const ConsultationsIdRouteChildren: ConsultationsIdRouteChildren = {
  ConsultationsIdDraftRoute: ConsultationsIdDraftRoute,
  ConsultationsIdNeedsRoute: ConsultationsIdNeedsRoute,
  ConsultationsIdSubmitRoute: ConsultationsIdSubmitRoute,
  ConsultationsIdIndexRoute: ConsultationsIdIndexRoute,
}

const ConsultationsIdRouteWithChildren = ConsultationsIdRoute._addFileChildren(
  ConsultationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  FamilyRoute: FamilyRouteWithChildren,
  HelpRoute: HelpRoute,
  IntegrationsRoute: IntegrationsRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  WorkshopsRoute: WorkshopsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ConsultationsIdRoute: ConsultationsIdRouteWithChildren,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
